services:
  ######################
  # RHTEST APP
  #############
  rhapi:
    build: ./rhapi
    container_name: rhapi
    ports:
      - 8080:8080

  rhfront:
    build:
      context: ./rhfront
      dockerfile: Dockerfile
      args:
        CODESPACE_NAME: ${CODESPACE_NAME}
        GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: ${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    container_name: rhfront
    ports:
      - 8086:80